### ISSUE TITLE
Swig is not currently maintained

### ISSUE THREAD

**Issue by MartinLogan** [koajs/error#19]
Per https://github.com/paularmstrong/swig and it currently uses an out of date Uglify.js that has a security vulnerability per nsp

Regular Expression Denial of Service

swig@1.4.2 > uglify-js@2.4.24
This is fixed in Uglify > 2.6.9

**Comment by coderhaoxin** [comment]
https://github.com/koajs/error/pull/13
https://github.com/koajs/error/pull/14

There are 2 PRs for this :)

**Comment by RavenHursT** [comment]
Can we get this merged and released?  Swig's out-of-date `uglify-js` is coming up as a security concern in our security scans.  Having to use `npm shrinkwrap` for now to override.

**Comment by coderhaoxin** [comment]
@RavenHursT will merge this in 24h! Sorry for the delay!

**Comment by coderhaoxin** [comment]
@RavenHursT May I ask you to review this [PR](https://github.com/koajs/error/pull/21),

just drop `swig`, and use [consolidate](https://github.com/tj/consolidate.js)

**Comment by RavenHursT** [comment]
Left some comments on the PR... Thanks @coderhaoxin :-)

**Comment by coderhaoxin** [comment]
closed by #23
