### ISSUE TITLE
Include a better default templating engine

### ISSUE THREAD

**Issue by RavenHursT** [koajs/error#23]
Per https://github.com/koajs/error/issues/19#issue-129886559, koa-error is defaulting to a library (Swig) that is no longer maintained, and also is causing `nsp` to error out due to an out-of-date `uglify-js` dependency.

Something more current, more widely used, and maintained should be swapped in.

I would suggest one of the following:

- ejs
- mustachJS
- handlebarsJS

Better yet.  This could just be done using ES6 JS string templating and remove the dependency all together ;-)

**Comment by coderhaoxin** [comment]
Just waiting more guys to give more advices!

**Comment by coderhaoxin** [comment]
ref: https://github.com/koajs/error/issues/1 https://github.com/koajs/error/issues/19

**Comment by RavenHursT** [comment]
Do we need a "bump" of some sort here?

**Comment by purepear** [comment]
> Better yet. This could just be done using ES6 JS string templating and remove the dependency all together ;-)
I agree

**Comment by nfantone** [comment]
@coderhaoxin Shall I review this?

**Comment by coderhaoxin** [comment]
@nfantone review what? (choose the better default templating engine?)

Maybe just use `string templating`?

**Comment by dantman** [comment]
ES6 string templates can't be passed anywhere, they're evaluated in-scope, so consolidate can't support them.
jade/pug seems popular, ejs could work but I haven't noticed many projects indicating they use it lately.

Of course there's always lodash. Lodash templates work pretty much like ES6 string templates, except they are actual strings/templates so they can be passed to consolidate and many people probably already have lodash somewhere in their dependency tree anyways.
